name: 📝 Draft release
description: Create a draft release
author: Quaternion Media
branding:
  icon: archive
  color: purple

runs:
  using: composite
  steps:
    - name: 🥌 Set milestone name
      run: echo MILESTONE_NAME=$(jq --raw-output .milestone.title $GITHUB_EVENT_PATH) >> $GITHUB_ENV
      shell: bash

    - name: ✏️ Set milestone description
      run: echo MILESTONE_DESCRIPTION=$(jq --raw-output .milestone.description $GITHUB_EVENT_PATH) >> $GITHUB_ENV
      shell: bash

    - name: 🏷️ Set tag name
      run: echo TAG_NAME=${MILESTONE_NAME%% *} >> $GITHUB_ENV
      shell: bash

    - name: 📦 Generate Release
      uses: softprops/action-gh-release@v1
      with:
        name: ${{ env.MILESTONE_NAME }}
        tag_name: ${{ env.TAG_NAME }}
        body: ${{ env.MILESTONE_DESCRIPTION }}
        generate_release_notes: true
        draft: true
