name: ðŸ“ Draft release
description: Create a draft release
author: Quaternion Media
branding:
  icon: archive
  color: purple

inputs:
  draft:
    description: Create release as a draft
    default: 'true'

runs:
  using: composite
  steps:
  # Set the release name from the milestone title
  - name: ðŸ¥Œ Set milestone name
    run: echo MILESTONE_NAME=$(jq --raw-output .milestone.title $GITHUB_EVENT_PATH) >> $GITHUB_ENV
    shell: bash
  # Set the release description from the milestone description
  - name: âœï¸ Set milestone description
    run: echo MILESTONE_DESCRIPTION=$(jq --raw-output .milestone.description $GITHUB_EVENT_PATH) >> $GITHUB_ENV
    shell: bash
  # Set the tag name from the first word of the milestone name
  - name: ðŸ·ï¸ Set tag name
    run: echo TAG_NAME=${MILESTONE_NAME%% *} >> $GITHUB_ENV
    shell: bash
  # Create a release using the GitHub Action
  - name: ðŸ“¦ Generate Release
    uses: softprops/action-gh-release@v2
    with:
      name: ${{ env.MILESTONE_NAME }}
      tag_name: ${{ env.TAG_NAME }}
      body: ${{ env.MILESTONE_DESCRIPTION }}
      generate_release_notes: true
      draft: ${{ inputs.draft }}
